# Generated by cucumber-sinatra. (2014-02-14 11:52:05 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/how_fucked_is_the_climate.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = HowFuckedIsTheClimate

class HowFuckedIsTheClimateWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  HowFuckedIsTheClimateWorld.new
end
