<div style="position: fixed; top: 0; left: 0; width: 200px; height: 100%; pointer-events:none; background: url(http://www.tomscott.com/buntify/bunting_l.png) top left repeat-y;"></div>
<div style="position: fixed; top: 0; right: 0; width: 200px; height: 100%; pointer-events:none; background: url(http://www.tomscott.com/buntify/bunting_r.png) top right repeat-y;"></div>
<div style="position: fixed; bottom: 0; left: 0; width: 100%; height: 200px; pointer-events:none; background: url(http://www.tomscott.com/buntify/bunting_d.png) bottom center no-repeat;"></div>
<embed autostart="true" loop="true" volume="100" hidden="false" src="http://www.tomscott.com/buntify/rulebrit.mid"></embed>
